DO
$do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'toto') THEN

      RAISE NOTICE 'Role "toto" already exists. Skipping.';
   ELSE
      CREATE ROLE toto LOGIN PASSWORD 'unGrosMotDePasse';
   END IF;
END
$do$;


CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR (50) UNIQUE NOT NULL,
  password VARCHAR (50) NOT NULL,
  first_name VARCHAR (50) NOT NULL,
  last_name VARCHAR (50) NOT NULL,
  email VARCHAR (255) UNIQUE NOT NULL
);

INSERT INTO users (id, username, password, email, first_name, last_name)
VALUES
(1234, 'toto', 'grosMotDePasse', 'toto@toto.com', 'toto', 'toto'),
(0, 'fdubois', 'P@ssw0rd92!', 'francois.dubois@gmail.com', 'François', 'Dubois'),
(1, 'lpelletier', 'L0u!s75#', 'lucie.pelletier@yahoo.com', 'Lucie', 'Pelletier'),
(2, 'gtremblay', 'S0ph!e84^', 'guy.tremblay@hotmail.com', 'Guy', 'Tremblay'),
(3, 'mmorin2', 'J@cques55&', 'marie.morin@outlook.com', 'Marie', 'Morin'),
(4, 'jlemieux', 'G3nev!e81%', 'jean.lemieux@aol.com', 'Jean', 'Lemieux'),
(5, 'cmartin', 'C@m!ll78&', 'carole.martin@live.com', 'Carole', 'Martin'),
(6, 'rcote', 'R0b3rt88+', 'renee.cote@icloud.com', 'Renée', 'Côté'),
(7, 'plavoie', 'P@tr!ck80|', 'pierre.lavoie@protonmail.com', 'Pierre', 'Lavoie'),
(8, 'sbergeron', 'J@l!3tt89(', 'sylvain.bergeron@me.com', 'Sylvain', 'Bergeron'),
(9, 'slapierre', 'Sylvi3!81*', 'sylvie.lapierre@live.fr', 'Sylvie', 'Lapierre'),
(10, 'mfortin', 'M@r!3&82', 'marc.fortin@yahoo.fr', 'Marc', 'Fortin'),
(11, 'sgagnon', 'S0ph!3G@uth!3r', 'sylvain.gagnon@hotmail.fr', 'Sylvain', 'Gagnon'),
(12, 'mpelletier', 'M!ch3ll3L3bl@nc', 'michel.pelletier@outlook.fr', 'Michel', 'Pelletier'),
(13, 'rgirard', 'R0b3rtF0rt!3r', 'rejean.girard@aol.fr', 'Réjean', 'Girard'),
(14, 'lbouchard', 'L#c!3&85', 'luc.bouchard@live.fr', 'Luc', 'Bouchard'),
(15, 'mlevesque', 'M@!3&82', 'martine.levesque@icloud.fr', 'Martine', 'Levesque'),
(16, 'rleblanc', 'R!ch@rdB0uch@rd', 'robert.leblanc@protonmail.fr', 'Robert', 'Leblanc'),
(17, 'mgagnon', 'M@r!3&82', 'mario.gagnon@me.fr', 'Mario', 'Gagnon'),
(18, 'rbergeronron', 'R0b3rt88+', 'rem.bergeron@yahoo.fr', 'Remi', 'Bergeron'),
(19, 'jlavoie', 'J@cqu3l!n3#87', 'jean.lavoie@hotmail.fr', 'Jean', 'Lavoie'),
(20, 'fcouture', 'F!3l!xL3f3vr3', 'francois.couture@outlook.fr', 'François', 'Couture'),
(21, 'ccaron', 'Ch@nt@l84=', 'claude.caron@aol.fr', 'Claude', 'Caron'),
(22, 'sfortin', 'S!m0nL3c0uvr3', 'stephane.fortin@live.fr', 'Stéphane', 'Fortin'),
(23, 'mbelanger', 'M@rc85$', 'martine.belanger@yahoo.fr', 'Martine', 'Bélanger'),
(24, 'jleclerc', 'J0s33!78~', 'jean.leclerc@icloud.fr', 'Jean', 'Leclerc'),
(25, 'rgaudreault', 'R0b3rt88+', 'rejean.gaudreault@protonmail.fr', 'Réjean', 'Gaudreault'),
(26, 'ldube', 'L#c!3&85', 'louis.dube@me.fr', 'Louis', 'Dubé'),
(27, 'blavoie', 'B3rn@rd79*', 'bernard.lavoie@live.fr', 'Bernard', 'Lavoie'),
(28, 'jrobita', 'J@n!3&82', 'jean.robitaille@hotmail.fr', 'Jean', 'Robitaille'),
(29, 'acaron', 'Ad3l3L@p!3rr3', 'andre.caron@outlook.fr', 'André', 'Caron'),
(30, 'rbergeron', 'R!3n!cL3g0ff', 'rejean.bergeron@aol.fr', 'Réjean', 'Bergeron'),
(31, 'pgauthier', 'P@ulGauth!3r', 'pierre.gauthier@live.fr', 'Pierre', 'Gauthier'),
(32, 'rbelanger', 'R!ch@rdB0uch@rd', 'robert.belanger@icloud.fr', 'Robert', 'Bélanger'),
(33, 'rgauthier', 'R3n3L3gr@nd', 'rejean.gauthier@me.fr', 'Réjean', 'Gauthier'),
(34, 'lmartel', 'L!s3M@r!3G@rt3n', 'luc.martel@yahoo.fr', 'Luc', 'Martel'),
(35, 'lmercier', 'L3g3nd3rL!nd3r', 'luc.mercier@hotmail.fr', 'Luc', 'Mercier'),
(36, 'tgagnon', 'T!b3r!0L3gr@nd', 'thomas.gagnon@outlook.fr', 'Thomas', 'Gagnon'),
(37, 'fredbergeron', 'Fr3d3r!c0L3c0uvr3', 'frederic.bergeron@live.fr', 'Frédéric', 'Bergeron'),
(38, 'pdubois', 'P@tr!ck80|', 'pierre.dubois@protonmail.fr', 'Pierre', 'Dubois'),
(39, 'jtremblay', 'J@!m3Tr0tt!3r', 'jean.tremblay@aol.fr', 'Jean', 'Tremblay'),
(41, 'lcote', 'L0r3ntD3s!gn3r', 'louis.cote@yahoo.fr', 'Louis', 'Côté'),
(42, 'pbouchard', 'P@tr!ck80|', 'pierre.bouchard@hotmail.fr', 'Pierre', 'Bouchard'),
(43, 'fgirard', 'Fr@nc01sB0urd!n', 'francois.girard@outlook.fr', 'François', 'Girard'),
(44, 'nrobert', 'N!c0l@sL3f3vr3', 'nicolas.robert@live.fr', 'Nicolas', 'Robert'),
(45, 'rcouture', 'R!ch@rdB0uch@rd', 'robert.couture@icloud.fr', 'Robert', 'Couture'),
(46, 'jmartel', 'J@!m3Tr0tt!3r', 'jacques.martel@aol.fr', 'Jacques', 'Martel'),
(47, 'sgauthier', 'S@ch@D!0n', 'simon.gauthier@outlook.fr', 'Simon', 'Gauthier'),
(48, 'llegault', 'L3gr@ndD3rn!3r', 'luc.legault@hotmail.fr', 'Luc', 'Legault'),
(49, 'msimard', 'M@rc!3L3v3rl!3ux', 'marie.simard@live.fr', 'Marie', 'Simard'),
(50, 'rlavoie', 'R!ch@rdB0uch@rd', 'roger.lavoie@icloud.fr', 'Roger', 'Lavoie'),
(51, 'tboucher', 'Th0m@sM0r!ss3@u', 'thomas.boucher@aol.fr', 'Thomas', 'Boucher'),
(52, 'lmorin', 'L0u!sL3gr@nd', 'luc.morin@outlook.fr', 'Luc', 'Morin'),
(53, 'lblanchard', 'L3gr@ndD3rn!3r', 'luc.blanchard@hotmail.fr', 'Luc', 'Blanchard'),
(54, 'gbergeron', 'G!ll3sB0urn3u!', 'gilles.bergeron@live.fr', 'Gilles', 'Bergeron'),
(55, 'jleduc', 'J0n@sD3s!gn3r', 'jean.leduc@yahoo.fr', 'Jean', 'Leduc'),
(56, 'gbelanger', 'G3r@m1L3c0nv0!s!3r', 'gaston.belanger@hotmail.fr', 'Gaston', 'Bélanger'),
(57, 'fpelletier', 'Fr@nc01sB0urd!n', 'francine.pelletier@outlook.fr', 'Francine', 'Pelletier'),
(58, 'mdesjardins', 'M@rc!3L3v3rl!3ux', 'marc.desjardins@live.fr', 'Marc', 'Desjardins'),
(59, 'ppoulin', 'P@tr!ck80|', 'paul.poulin@icloud.fr', 'Paul', 'Poulin'),
(60, 'cdube', 'Ch@rl3L3cl3rc', 'claire.dube@aol.fr', 'Claire', 'Dubé'),
(61, 'lgagnon', 'L0u!sL3gr@nd', 'luc.gagnon@outlook.fr', 'Luc', 'Gagnon'),
(62, 'lsimarde', 'L3gr@ndD3rn!3r', 'lucie.simard@hotmail.fr', 'Lucie', 'Simard'),
(63, 'jrobert', 'J0n@sD3s!gn3r', 'josee.robert@yahoo.fr', 'Josée', 'Robert'),
(64, 'scaron', 'S!m0nM0nt3r3g!3nn3', 'sylvain.caron@live.fr', 'Sylvain', 'Caron'),
(65, 'jcoutu', 'J@!m3Tr0tt!3r', 'j.coutu@outlook.fr', 'Jean', 'Coutu'),
(66, 'jbergeron3', 'J0n@sD3s!gn3r', 'jeannne.bergeron@icloud.fr', 'Jeanne', 'Bergeron'),
(67, 'jfortin2', 'J0n@sD3s!gn3r', 'jacqueline.fortin@aol.fr', 'Jacqueline', 'Fortin'),
(68, 'mgirard', 'M@rc!3L3v3rl!3ux', 'michelle.girard@hotmail.fr', 'Michelle', 'Girard'),
(69, 'mdesrosiers', 'M@rc!3L3v3rl!3ux', 'marie.desrosiers@outlook.fr', 'Marie', 'Desrosiers'),
(70, 'lemond', 'L3gr@ndD3rn!3r', 'luc.lemond@live.fr', 'Luc', 'Lemond'),
(71, 'blachance', 'B3rn@rd79*', 'bernard.lachance@icloud.fr', 'Bernard', 'Lachance'),
(72, 'jprevost', 'J0n@sD3s!gn3r', 'jean.prevost@aol.fr', 'Jean', 'Prévost'),
(73, 'nbergeron', 'N!c0l@sL3f3vr3', 'nicole.bergeron@yahoo.fr', 'Nicole', 'Bergeron'),
(74, 'gbeaulieu', 'G3r@m1L3c0nv0!s!3r', 'gaston.beaulieu@hotmail.fr', 'Gaston', 'Beaulieu'),
(75, 'tfortin', 'Th0m@sM0r!ss3@u', 'thomas.fortin@outlook.fr', 'Thomas', 'Fortin'),
(76, 'pbergeron', 'P!3rr3D3s!gn3r', 'pierre.bergeron@live.fr', 'Pierre', 'Bergeron'),
(77, 'llemieux', 'L3gr@ndD3rn!3r', 'luc.lemieux@aol.fr', 'Luc', 'Lemieux'),
(100, 'pgagnon', 'P@tr!ck80|', 'paul.gagnon@icloud.fr', 'Paul', 'Gagnon'),
(78, 'mmorin', 'M!ch3ll3L3bl@nc', 'marc.morin@hotmail.fr', 'Marc', 'Morin'),
(80, 'vbergeron', 'V!nc3ntL3cl3rc', 'vincent.bergeron@outlook.fr', 'Vincent', 'Bergeron'),
(81, 'lbeaudoin', 'L0u!sL3gr@nd', 'luc.beaudoin@hotmail.fr', 'Luc', 'Beaudoin'),
(82, 'dbelanger', 'D3s!r3L3c0uvr3', 'daniel.belanger@live.fr', 'Daniel', 'Bélanger'),
(83, 'jdesrosiers', 'J@!m3Tr0tt!3r', 'jean.desrosiers@aol.fr', 'Jean', 'Desrosiers'),
(84, 'ctremblay', 'Ch@rl3L3cl3rc', 'claire.tremblay@outlook.fr', 'Claire', 'Tremblay'),
(85, 'rfournier', 'R0b3rt88+', 'rejean.fournier@yahoo.fr', 'Réjean', 'Fournier'),
(86, 'gblais', 'G3r@m1L3c0nv0!s!3r', 'gaston.blais@hotmail.fr', 'Gaston', 'Blais'),
(87, 'jrobitaille', 'J0n@sD3s!gn3r', 'josee.robitaille@live.fr', 'Josée', 'Robitaille'),
(88, 'lplamondon', 'L0u!sL3gr@nd', 'luc.plamondon@aol.fr', 'Luc', 'Plamondon'),
(89, 'mchampagne', 'M!ch3ll3L3bl@nc', 'martine.champagne@outlook.fr', 'Martine', 'Champagne'),
(90, 'ldenis', 'L3gr@ndD3rn!3r', 'luc.denis@hotmail.fr', 'Luc', 'Denis'),
(91, 'fbergeron', 'Fr@nc01sB0urd!n', 'francois.bergeron@yahoo.fr', 'François', 'Bergeron'),
(92, 'lsimard', 'L3gr@ndD3rn!3r', 'luc.somard@live.fr', 'Luc', 'Simard'),
(93, 'dgagnon', 'D3s!r3L3c0uvr3', 'daniel.gagnon@aol.fr', 'Daniel', 'Gagnon'),
(94, 'jcote', 'J@!m3Tr0tt!3r', 'jean.cote@outlook.fr', 'Jean', 'Côté'),
(95, 'mmorin1', 'M!ch3ll3L3bl@nc', 'marie1.morin@hotmail.fr', 'Marielle', 'Morin'),
(96, 'jbergeron', 'J0n@sD3s!gn3r', 'jean.bergeron@icloud.fr', 'Jean', 'Bergeron'),
(97, 'jfortin', 'J0n@sD3s!gn3r', 'jacques.fortin@aol.fr', 'Jacques', 'Fortin'),
(98, 'mgirardd', 'M@rc!3L3v3rl!3ux', 'michel.girard@hotmail.fr', 'Michel', 'Girard'),
(99, 'mlledesrosiers', 'M@rc!3L3v3rl!3ux', 'marielle.desrosiers@outlook.fr', 'Marielle', 'Desrosiers');
